version: '3.3'

services:
  postgres:
    image: postgres:14.3
    container_name: raffle_database
    restart: always
    expose:
      - 5432
    env_file:
      - ".env"
    ports:
      - "5433:5432"

  redis:
    image: redis:7.0
    container_name: raffle_redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./cache:/data
    expose:
      - 6379

  bot:
    build: ./app
    container_name: raffle_bot
    stop_signal: SIGINT
    command: python bot.py
    restart: always
    env_file:
      - ".env"
    volumes:
      - ./app:/app
    depends_on:
      - postgres
      - redis
