version: '3.3'

services:
  postgres:
    image: postgres:14.3
    container_name: database_raffle
    expose:
      - 5432
    env_file:
      - ".env"
    ports:
      - 5433:5432

  bot:
    build: ./app
    container_name: raffle_bot
    stop_signal: SIGINT
    command: python bot.py
    restart: always
    env_file:
      - ".env"
    volumes:
      - ./app:/app
    depends_on:
      - postgres
